### ISSUE TITLE
Just reaching out to share our media query parser

### ISSUE THREAD

**Issue by romainmenke** [tbjgolden/media-query-parser#10]
See : https://github.com/csstools/postcss-plugins/tree/main/packages/media-query-list-parser

It seems we both created parsers for the same reason :)
Our test suite or some implementation details might be interesting for your package.

_You can close this after reading._

**Comment by tbjgolden** [comment]
Excellent, thanks! Gonna look over it and see if there's anything I missed.

One thing to be aware of in the spec was that there must not be a space between `<` and `=` (and `>` and `=`); it seemed to be the only place where an explicit check for whitespace is needed

**Comment by romainmenke** [comment]
> One thing to be aware of in the spec was that there must not be a space between < and = (and > and =); it seemed to be the only place where an explicit check for whitespace is needed

Correct :)

You can observe this in the transpilation of range query syntax.  
When there is a space it will be invalid and it will be ignored.

https://preset-env.cssdb.org/playground/#eyJzb3VyY2UiOiJAbWVkaWEgKDQ4cmVtIDw9IHdpZHRoKSB7XG5cdC5mb28ge31cbn1cblxuQG1lZGlhICg0OHJlbSA8ID0gd2lkdGgpIHtcblx0LmZvbyB7fVxufVxuIiwiY29uZmlnIjp7ImJyb3dzZXJzIjpbIj4gMC4yJSBhbmQgbm90IGRlYWQiXSwibWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyI6MCwic3RhZ2UiOjIsImxvZ2ljYWwiOnsiaW5saW5lRGlyZWN0aW9uIjoibGVmdC10by1yaWdodCIsImJsb2NrRGlyZWN0aW9uIjoidG9wLXRvLWJvdHRvbSJ9fX0%3D
