### ISSUE TITLE
Creating media query string from ast

### ISSUE THREAD

**Issue by Townsheriff** [tbjgolden/media-query-parser#3]
Hi,

I checked the library and it looks really good, but I did not see an option to generate mediaQuery from ast.

I'm looking for a way where I can modify query string by creating an AST updating it and then generating media query string to be consumed by `window.mediaQuery`.

Is this something I missed when checking, or it is planned to implement in the future?

Cheers,
Arturs

**Comment by tbjgolden** [comment]
Hi Arturs,

That's a good idea. I stopped looking at this repo a few months ago and returned to see 100k weekly downloads on npm - so I probably ought to update this project a little :)

So to answer your question:

There is not - as far as I know - a generator for this AST, but I will look at creating one. If I do, it will be released as a separate package and not in this package.

Tom

**Comment by tbjgolden** [comment]
fixed in https://github.com/tbjgolden/media-query-parser/releases/tag/v3.0.0-beta.0

use the `stringify()` function (requires an AST generated from v3+) 😄
